version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: documantis-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=documantis
      - POSTGRES_PASSWORD=documantis
      - POSTGRES_DB=documantis
    restart: unless-stopped
    networks:
      - documantis-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U documantis"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: documantis-backend
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./app:/app/app
      - ./app/migrations:/app/migrations
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=documantis
      - DB_PASSWORD=documantis
      - DB_NAME=documantis
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - documantis-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: documantis-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - documantis-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  documantis-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  postgres-data:
    driver: local
